server:
  port: 8081

spring:
  application:
    name: spring-app2
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.app2: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"